name: Common JS CI

on:
  schedule:
    - cron: '0 0 * * *'
  push:
    branches: [ master ]
    tags: [ 'v[0-9]+.[0-9]+.[0-9]+' ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node: [ 14, 16, 18, 20 ]
        os: [ macos-latest, ubuntu-latest, windows-latest ]
        exclude:
          - node: 14
            os: macos-latest
      fail-fast: false
    name: Test [${{ matrix.os }}, Node ${{ matrix.node }}]
    steps:
      - uses: actions/checkout@v5

      - uses: actions/setup-node@v5
        with:
          node-version: ${{ matrix.node }}

      - name: Install dependencies
        run: |
          npm install

      - name: Build
        run: npm run build

      - name: Test
        run: npm run test

      - name: Archive
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: checked-out-lib
          path: lib

  coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - uses: actions/setup-node@v5
        with:
          node-version: 14

      - name: Install dependencies
        run: |
          npm install codecov -g
          npm install

      - name: Build
        run: npm run build

      - name: Coverage
        run: npm run coverage

      - name: Upload coverage report
        run: codecov

  publish:
    needs: [ test, coverage ]
    if: startsWith(github.ref, 'refs/tags')
    runs-on: ubuntu-latest
    permissions:
      id-token: write # Required for OIDC (see also https://docs.npmjs.com/trusted-publishers)
      contents: read
    steps:
      - uses: actions/checkout@v5

      - uses: actions/setup-node@v5
        with:
          node-version: 22
          registry-url: 'https://registry.npmjs.org'

      # Ensure npm 11.5.1 or later is installed
      - name: Update npm
        run: npm install -g npm@latest

      - name: Install dependencies & build
        run: npm install

      - name: 🚀Publish
        run: npm publish
